name: 'Get PR Number'
description: 'Get PR number from a string'
inputs:
  pr_string:
    description: 'The string to extract PR number from'
    required: true
outputs:
  pr_number:
    description: 'The extracted PR number'
    value: ${{ steps.get_pr_number.outputs.pr_number }}
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: bash get_pr_number.sh ${{ inputs.pr_string }}
      id: get_pr_number
      shell: bash
